### ISSUE TITLE
RuntimeError: generator raised StopIteration when preprocessing for Conversational models

### ISSUE THREAD

**Issue by jatinganhotra** [stanfordnlp/coqa-baselines#7]
```
python seq2seq/preprocess.py -train_src data/seq2seq-train-h2-src.txt -train_tgt data/seq2seq-train-h2-tgt.txt -valid_src data/seq2seq-dev-h2-src.txt -valid_tgt data/seq2seq-dev-h2-tgt.txt -save_data data/seq2seq-h2 -lower -dynamic_dict -src_seq_length 10000

[2018-12-30 10:40:29,810 INFO] Extracting features...
[2018-12-30 10:40:29,812 INFO]  * number of source features: 0.
[2018-12-30 10:40:29,812 INFO]  * number of target features: 0.
[2018-12-30 10:40:29,812 INFO] Building `Fields` object...
[2018-12-30 10:40:29,812 INFO] Building & saving training data...
Traceback (most recent call last):
  File "/Users/jatinganhotra/deep-learning/CoQA/coqa-baselines/seq2seq/onmt/io/TextDataset.py", line 368, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "seq2seq/preprocess.py", line 204, in <module>
    main()
  File "seq2seq/preprocess.py", line 194, in main
    train_dataset_files = build_save_dataset('train', fields, opt, logger)
  File "seq2seq/preprocess.py", line 134, in build_save_dataset
    corpus_type, opt)
  File "seq2seq/preprocess.py", line 103, in build_save_text_dataset_in_shards
    dynamic_dict=opt.dynamic_dict)
  File "/Users/jatinganhotra/deep-learning/CoQA/coqa-baselines/seq2seq/onmt/io/TextDataset.py", line 78, in __init__
    for ex_values in example_values:
  File "/Users/jatinganhotra/deep-learning/CoQA/coqa-baselines/seq2seq/onmt/io/TextDataset.py", line 70, in <genexpr>
    example_values = ([ex[k] for k in keys] for ex in examples_iter)
  File "/Users/jatinganhotra/deep-learning/CoQA/coqa-baselines/seq2seq/onmt/io/TextDataset.py", line 271, in _dynamic_dict
    for example in examples_iter:
  File "/Users/jatinganhotra/deep-learning/CoQA/coqa-baselines/seq2seq/onmt/io/TextDataset.py", line 56, in <genexpr>
    examples_iter = (self._join_dicts(src, tgt) for src, tgt in
RuntimeError: generator raised StopIteration
```
The version for packages installed are:
```
→ python -V
Python 3.7.1

→ pip list
Package         Version
--------------- ----------
boto            2.49.0
boto3           1.9.71
botocore        1.12.71
bz2file         0.98
certifi         2018.11.29
cffi            1.11.5
chardet         3.0.4
docutils        0.14
gensim          3.6.0
idna            2.8
jmespath        0.9.3
mkl-fft         1.0.6
mkl-random      1.0.2
numpy           1.15.4
olefile         0.46
Pillow          5.3.0
pip             18.1
pycorenlp       0.3.0
pycparser       2.19
python-dateutil 2.7.5
requests        2.21.0
s3transfer      0.1.13
scipy           1.2.0
setuptools      40.6.3
six             1.12.0
smart-open      1.7.1
torch           1.0.0
torchtext       0.2.1
torchvision     0.2.1
tqdm            4.28.1
urllib3         1.24.1
wheel           0.32.3
```

**Comment by Gpwner** [comment]
Do you figure it out?Cause I got the same error.

**Comment by Gpwner** [comment]
Finally，Ifigure it out.Because the Python version，Just change  to python3.6.8, and it works.
